name: Laravel Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    # Definimos un servicio MySQL para que las pruebas se ejecuten contra una base de datos real.
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: lavcauqu_lav_db_test
          MYSQL_USER: lavcauqu_admin_lav
          MYSQL_PASSWORD: @vZPH)X6=HrB
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=3

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, pdo, mysql, xml, curl

      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: Generate Application Key
        run: php artisan key:generate

      - name: Run Migrations
        env:
          DB_CONNECTION: mysql
          DB_HOST: 186.64.114.110
          DB_PORT: 3306
          DB_DATABASE: lavcauqu_lav_db_test
          DB_USERNAME: lavcauqu_admin_lav
          DB_PASSWORD: @vZPH)X6=HrB
        run: php artisan migrate --force

      - name: Run Tests
        env:
          DB_CONNECTION: mysql
          DB_HOST: 186.64.114.110
          DB_PORT: 3306
          DB_DATABASE: lavcauqu_lav_db_test
          DB_USERNAME: lavcauqu_admin_lav
          DB_PASSWORD: @vZPH)X6=HrB
        run: php artisan test
